import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API='http://127.0.0.1:8000';
function getToken(){return localStorage.getItem('token')||''}
async function api(path, opts={}){
  const res=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',Authorization:'Bearer '+getToken(),...(opts.headers||{})}});
  if(!res.ok){let e=await res.text(); throw new Error(e)}
  return res.json();
}
function App(){
  const [token,setToken]=useState(getToken());
  const [company,setCompany]=useState(JSON.parse(localStorage.getItem('company')||'null'));
  const [screen,setScreen]=useState(token?(company?'dashboard':'companies'):'login');
  useEffect(()=>{function key(e){
    const k=e.key.toLowerCase();
    if(e.ctrlKey&&k==='h'){e.preventDefault();setScreen('dashboard')}
    if(e.ctrlKey&&k==='q'){e.preventDefault();logout()}
    if(e.altKey&&k==='l'){e.preventDefault();setScreen('ledgers')}
    if(e.altKey&&k==='s'){e.preventDefault();setScreen('stock')}
    if(e.key==='F8'){e.preventDefault();setScreen('sales')}
    if(e.key==='F9'){e.preventDefault();setScreen('purchase')}
    if(e.ctrlKey&&k==='r'){e.preventDefault();setScreen('reports')}
    if(e.key==='F1'){e.preventDefault();setScreen('companies')}
  } window.addEventListener('keydown',key); return()=>window.removeEventListener('keydown',key)},[]);
  function onLogin(t){localStorage.setItem('token',t); setToken(t); setScreen('companies')}
  function openCompany(c){localStorage.setItem('company',JSON.stringify(c)); setCompany(c); setScreen('dashboard')}
  function logout(){localStorage.clear(); setToken(''); setCompany(null); setScreen('login')}
  if(!token) return screen==='register'?<Register goLogin={()=>setScreen('login')} onLogin={onLogin}/>:<Login goRegister={()=>setScreen('register')} onLogin={onLogin}/>;
  if(!company || screen==='companies') return <Companies openCompany={openCompany} logout={logout}/>;
  return <Layout screen={screen} setScreen={setScreen} company={company} setCompany={setCompany} logout={logout}/>;
}
function Login({goRegister,onLogin}){const [email,setEmail]=useState('admin@smarterp.com'),[password,setPassword]=useState('admin123'),[err,setErr]=useState('');async function submit(e){e.preventDefault();try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(r.token)}catch(x){setErr('Invalid login. Try admin@smarterp.com / admin123')}}return <div className="auth"><form onSubmit={submit} className="card authcard"><h1>SmartERP Login</h1><p>Billing, Inventory & Accounting Management System</p>{err&&<div className="err">{err}</div>}<label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} autoFocus/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Login</button><button type="button" className="linkbtn" onClick={goRegister}>Register New User</button></form></div>}
function Register({goLogin,onLogin}){const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');async function submit(e){e.preventDefault();try{const r=await api('/auth/register',{method:'POST',body:JSON.stringify({name,email,password})});onLogin(r.token)}catch(x){setErr('Registration failed. Email may already exist.')}}return <div className="auth"><form onSubmit={submit} className="card authcard"><h1>Register User</h1>{err&&<div className="err">{err}</div>}<label>Name</label><input value={name} onChange={e=>setName(e.target.value)} required autoFocus/><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} required/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Create Account</button><button type="button" className="linkbtn" onClick={goLogin}>Back to Login</button></form></div>}
function Companies({openCompany,logout}){const [companies,setCompanies]=useState([]),[form,setForm]=useState({name:'',address:'',gst_number:'',financial_year:'2026-2027',state:'Maharashtra',contact:''});async function load(){setCompanies(await api('/companies'))}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();await api('/companies',{method:'POST',body:JSON.stringify(form)});setForm({...form,name:''});load()}async function del(id){if(confirm('Delete company?')){await api('/companies/'+id,{method:'DELETE'});load()}}return <div className="page"><header><h1>Company Selection</h1><button onClick={logout}>Logout</button></header><div className="grid2"><form onSubmit={add} className="card"><h2>Create / Register Company</h2><input placeholder="Company Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input placeholder="GST Number" value={form.gst_number} onChange={e=>setForm({...form,gst_number:e.target.value})}/><input placeholder="Financial Year" value={form.financial_year} onChange={e=>setForm({...form,financial_year:e.target.value})}/><input placeholder="State" value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/><input placeholder="Contact" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/><button>Register Company</button></form><div className="card"><h2>Select Company</h2>{companies.length===0?<p>No company found. Create one.</p>:companies.map(c=><div className="row" key={c.id}><div><b>{c.name}</b><br/><small>{c.financial_year} | {c.state}</small></div><button onClick={()=>openCompany(c)}>Open</button><button className="danger" onClick={()=>del(c.id)}>Delete</button></div>)}</div></div></div>}
function Layout({screen,setScreen,company,setCompany,logout}){return <div className="app"><aside><h2>SmartERP</h2><p>{company.name}</p><button onClick={()=>setScreen('dashboard')}>Dashboard Ctrl+H</button><button onClick={()=>setScreen('ledgers')}>Ledgers Alt+L</button><button onClick={()=>setScreen('stock')}>Item / Stock Alt+S</button><button onClick={()=>setScreen('sales')}>Sales Voucher F8</button><button onClick={()=>setScreen('purchase')}>Purchase Voucher F9</button><button onClick={()=>setScreen('reports')}>Reports Ctrl+R</button><button onClick={()=>{localStorage.removeItem('company');setCompany(null)}}>F1 Company</button><button onClick={logout}>Logout Ctrl+Q</button></aside><main>{screen==='dashboard'&&<Dashboard company={company}/>} {screen==='ledgers'&&<Ledgers company={company}/>} {screen==='stock'&&<Stock company={company}/>} {screen==='sales'&&<Voucher company={company} type="Sales"/>} {screen==='purchase'&&<Voucher company={company} type="Purchase"/>} {screen==='reports'&&<Reports company={company}/>}</main></div>}
function Dashboard({company}){const [d,setD]=useState(null);useEffect(()=>{api('/dashboard/'+company.id).then(setD)},[company]);if(!d)return <p>Loading...</p>;return <div><h1>Gateway of SmartERP</h1><div className="cards"><div className="card"><h3>Total Sales</h3><b>₹{d.total_sales}</b></div><div className="card"><h3>Total Purchase</h3><b>₹{d.total_purchases}</b></div><div className="card"><h3>Stock Items</h3><b>{d.stock_items}</b></div><div className="card"><h3>Ledgers</h3><b>{d.ledgers}</b></div></div><div className="card"><h2>Low Stock</h2>{d.low_stock.length?d.low_stock.map(i=><p key={i.id}>{i.name}: {i.quantity}</p>):<p>No low stock items</p>}</div></div>}
function Ledgers({company}){const [list,setList]=useState([]),[form,setForm]=useState({name:'',ledger_type:'Customer',mobile:'',gst_number:'',address:'',opening_balance:0});async function load(){setList(await api('/ledgers/'+company.id))}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();await api('/ledgers/'+company.id,{method:'POST',body:JSON.stringify({...form,opening_balance:Number(form.opening_balance)})});setForm({...form,name:'',mobile:'',gst_number:'',address:'',opening_balance:0});load()}return <div><h1>Ledger Management</h1><form onSubmit={add} className="card formrow"><input placeholder="Ledger Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><select value={form.ledger_type} onChange={e=>setForm({...form,ledger_type:e.target.value})}>{['Customer','Supplier','Expense','Income','Bank','Cash'].map(x=><option>{x}</option>)}</select><input placeholder="Mobile" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/><input placeholder="GST" value={form.gst_number} onChange={e=>setForm({...form,gst_number:e.target.value})}/><input type="number" placeholder="Opening Balance" value={form.opening_balance} onChange={e=>setForm({...form,opening_balance:e.target.value})}/><button>Add Ledger</button></form><Table rows={list} cols={['id','name','ledger_type','mobile','gst_number','current_balance']}/></div>}
function Stock({company}){const [list,setList]=useState([]),[form,setForm]=useState({name:'',sku:'',hsn_code:'',unit:'PCS',purchase_price:0,selling_price:0,quantity:0,gst_percent:18,reorder_level:5});async function load(){setList(await api('/items/'+company.id))}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();const f={...form,purchase_price:Number(form.purchase_price),selling_price:Number(form.selling_price),quantity:Number(form.quantity),gst_percent:Number(form.gst_percent),reorder_level:Number(form.reorder_level)};await api('/items/'+company.id,{method:'POST',body:JSON.stringify(f)});setForm({...form,name:'',sku:''});load()}return <div><h1>Item / Stock Master</h1><form onSubmit={add} className="card formrow"><input placeholder="Item Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="SKU" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><input placeholder="HSN" value={form.hsn_code} onChange={e=>setForm({...form,hsn_code:e.target.value})}/><input placeholder="Unit" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input type="number" placeholder="Purchase Price" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/><input type="number" placeholder="Selling Price" value={form.selling_price} onChange={e=>setForm({...form,selling_price:e.target.value})}/><input type="number" placeholder="Qty" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input type="number" placeholder="GST %" value={form.gst_percent} onChange={e=>setForm({...form,gst_percent:e.target.value})}/><button>Add Item</button></form><Table rows={list} cols={['id','name','sku','hsn_code','unit','purchase_price','selling_price','quantity','gst_percent']}/></div>}
function Voucher({company,type}){const [ledgers,setLedgers]=useState([]),[items,setItems]=useState([]),[vouchers,setVouchers]=useState([]),[form,setForm]=useState({party_ledger_id:'',item_id:'',quantity:1,rate:0,narration:''});async function load(){const l=await api('/ledgers/'+company.id), i=await api('/items/'+company.id), v=await api('/vouchers/'+company.id);setLedgers(l.filter(x=>type==='Sales'?x.ledger_type==='Customer':x.ledger_type==='Supplier'));setItems(i);setVouchers(v.filter(x=>x.voucher_type===type)); if(!form.party_ledger_id&&l.length)setForm(f=>({...f,party_ledger_id:(l.filter(x=>type==='Sales'?x.ledger_type==='Customer':x.ledger_type==='Supplier')[0]||{}).id||''})); if(!form.item_id&&i.length)setForm(f=>({...f,item_id:i[0].id,rate:type==='Sales'?i[0].selling_price:i[0].purchase_price}))}useEffect(()=>{load()},[type]);function itemChange(id){let it=items.find(x=>x.id==id);setForm({...form,item_id:id,rate:it?(type==='Sales'?it.selling_price:it.purchase_price):0})}async function add(e){e.preventDefault();await api('/vouchers/'+company.id,{method:'POST',body:JSON.stringify({voucher_type:type,party_ledger_id:Number(form.party_ledger_id),item_id:Number(form.item_id),quantity:Number(form.quantity),rate:Number(form.rate),narration:form.narration})});setForm({...form,quantity:1,narration:''});load()}return <div><h1>{type} Voucher {type==='Sales'?' / Customer Bill':' / Indirect Stock Entry'}</h1><form onSubmit={add} className="card formrow"><select value={form.party_ledger_id} onChange={e=>setForm({...form,party_ledger_id:e.target.value})}>{ledgers.map(l=><option value={l.id}>{l.name}</option>)}</select><select value={form.item_id} onChange={e=>itemChange(e.target.value)}>{items.map(i=><option value={i.id}>{i.name} (Stock {i.quantity})</option>)}</select><input type="number" placeholder="Qty" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input type="number" placeholder="Rate" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/><input placeholder="Narration" value={form.narration} onChange={e=>setForm({...form,narration:e.target.value})}/><button>Create {type}</button></form><Table rows={vouchers} cols={['id','voucher_no','voucher_type','quantity','rate','amount','tax','total']}/>{vouchers[0]&&<a className="download" href={API+'/invoice/'+vouchers[0].id+'/pdf'} target="_blank">Download Latest Invoice PDF</a>}</div>}
function Reports({company}){const [r,setR]=useState(null);useEffect(()=>{api('/reports/'+company.id).then(setR)},[]);if(!r)return <p>Loading reports...</p>;return <div><h1>Reports</h1><a className="download" href={API+'/export/'+company.id+'/excel'}>Download Excel Stock Report</a><h2>Trial Balance</h2><Table rows={r.trial_balance} cols={['ledger','type','balance']}/><h2>Stock Summary</h2><Table rows={r.stock_summary} cols={['item','qty','value']}/><h2>Sales Register</h2><Table rows={r.sales_register} cols={['voucher_no','quantity','amount','tax','total']}/><h2>Purchase Register</h2><Table rows={r.purchase_register} cols={['voucher_no','quantity','amount','tax','total']}/></div>}
function Table({rows,cols}){return <div className="card tablewrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>):<tr><td colSpan={cols.length}>No data</td></tr>}</tbody></table></div>}
createRoot(document.getElementById('root')).render(<App/>);
